version: '3.7'

services:

  web:
    image: ghcr.io/xdock/php-app:8.2-2024.01
    command: run-services web
    environment:
      APP_NAME: demo-docker-compose-laravel-dusk
      APP_ENV: local
    ports:
      - "8000:80"
    volumes:
      - .:/app
    networks:
      default:
        aliases:
          - web.testing

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    volumes:
      - ./.docker/mysql/init-testing-db.sh:/docker-entrypoint-initdb.d/init-testing-db.sh

  selenium:
    image: seleniarm/standalone-chromium
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
